### PR TITLE
Update OpenCV dependencies

### PR DESCRIPTION
**Pull request by jhkennedy**
### Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### Why
This relaxes the `opencv` host dependency (previously pinned at 3.4) as it works with both OpenCV 3.4 and 4, and pins the runtime dependency to the version of OpenCV autoRIFT was built against. 

I've also eliminated `libopencv` from the recipe as [it's a pinned dependency of `opencv`](https://github.com/conda-forge/opencv-feedstock/blob/master/recipe/meta.yaml#L178)

### CODE REVIEW

**Comment by jhkennedy** [comment]
@conda-forge-admin, please rerender

**Comment by piyushrpt** [comment]
I believe - the package might need to be called py-opencv in the build section, as opencv itself doesnt impose any build requirements ? 
https://github.com/conda-forge/opencv-feedstock/blob/master/recipe/meta.yaml

**Comment by piyushrpt** [comment]
opencv4 gets installed under `$PREFIX/include/opencv4` - see build.sh on isce2-feedstock. One can explicitly add this to CPPFLAGS during the installation or with --global-option. If that doesnt work, might have to just add a simple build.sh where the options can be set.

**Comment by jhkennedy** [comment]
Thanks @piyushrpt! That'll fix it.

**Review by piyushrpt — APPROVED** [review]

**Review by leiyangleon — APPROVED** [review]

**Pull request merged**
