### PR TITLE
Bump autoRIFT to v1.5.0

### PR DESCRIPTION
**Pull request by jhkennedy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jhkennedy** [comment]
@conda-forge-admin, please rerender

**Comment by jhkennedy** [comment]
@conda-forge-admin, please rerender

**Comment by jhkennedy** [comment]
@conda-forge-admin, please rerender

**Comment by jhkennedy** [comment]
Note: Python 3.9 build failed because it was built against opencv 4.5.5, but verified with opencv 4.6.0 installed in the environment, which caused a linking issue. here's the docs to `pin_compatible`: https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2

**Comment by jhkennedy** [comment]
harumph, that fixed linux+py39 but now linux+py310 is failing with:
```
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - scipy
 - scikit-image
 - libgdal >=3.5.3,<3.6.0a0
 - python >=3.10,<3.11.0a0
 - python_abi 3.10.* *_cp310
 - gdal
 - libgcc-ng >=12
 - opencv >=4.5.5,<4.6.0a0
 - libstdcxx-ng >=12

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package gdal-3.5.3-py310hb7951cf_0 requires openssl >=1.1.1q,<1.1.2a, but none of the providers can be installed
```

**Comment by jhkennedy** [comment]
Re-ran the action and all builds passed -- notably in the failed p310 build, opencv 4.6 was installed in the build environment but the pin was stale `opencv >=4.5.5,<4.6.0a0`. Should be g2g.

**Review by jacquelynsmale — APPROVED** [review]

**Pull request merged**
